CREATE TABLE IF NOT EXISTS users (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    email   VARCHAR(254) NOT NULL UNIQUE,
    name    VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name    VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    annotation          VARCHAR(2000),
    category_id         BIGINT,
    confirmed_requests  INTEGER NOT NULL DEFAULT 0,
    created             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    description         TEXT,
    event_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id        BIGINT,
    location_lat        FLOAT NOT NULL DEFAULT 0.0,
    location_lon        FLOAT NOT NULL DEFAULT 0.0,
    paid                BOOLEAN NOT NULL DEFAULT false,
    participant_limit   INTEGER NOT NULL DEFAULT 0,
    publish_date        TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    request_moderation  BOOLEAN NOT NULL DEFAULT false,
    state               VARCHAR(50) NOT NULL,
    title               VARCHAR(150) NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (initiator_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pinned  BOOLEAN NOT NULL,
    name    VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id  BIGINT NOT NULL,
    event_id        BIGINT NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_id        BIGINT NOT NULL,
    requester_id    BIGINT NOT NULL,
    status          VARCHAR(50) NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE
);